import Head from "next/head";
import { FaRegCalendar } from "react-icons/fa";
import { DatePicker } from 'antd';
import { useState } from "react";
import { IoMdArrowDropdown } from "react-icons/io";
import { IoPersonSharp } from "react-icons/io5";
import { FaArrowRightLong } from "react-icons/fa6";
import { GoPlus } from "react-icons/go";
import { FiMinus } from "react-icons/fi";
import { useRouter } from "next/router";

const { RangePicker } = DatePicker;
type TBookingData = {
  adult: number;
  children: number;
  room: number;
}
export default function Home() {
  const router = useRouter();
  const [isShowOption, setShowOption] = useState<boolean>(false);
  const [bookingTime, setBookingTime] = useState<string[]>([]);
  const [bookingData, setBookingData] = useState<TBookingData>({ adult: 1, children: 0, room: 1 });
  function handleChangeNumber({ key, value }: { key: string, value: number }) {
    switch (key) {
      case 'adult':
        setBookingData(prev => ({ ...prev, adult: (value === -1 && prev.adult < 1) ? 0 : prev.adult + value }))
        break;
      case 'child':
        setBookingData(prev => ({ ...prev, children: (value === -1 && prev.children < 1) ? 0 : prev.children + value }))
        break;
      case 'room':
        setBookingData(prev => ({ ...prev, room: (value === -1 && prev.room < 1) ? 0 : prev.room + value }))
        break;
    }
  }
  function handleBooking() {
    if (bookingTime.length !== 2) {
      alert('Vui long chon ngay thang');
      return;
    }
    if (bookingData.adult === 0 && bookingData.room === 0) {
      alert('So luong nguoi hoac phong dang bang 0')
      return;
    }

    router.push(`/booking?st=${bookingTime[0]}&et=${bookingTime[1]}&a=${bookingData.adult}&c=${bookingData.children}&r=${bookingData.room}`)
  }
  return (
    <>
      <Head>
        <title>Khách sạn Lạc Hồng</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container d-flex justify-content-center align-items-center" style={{ height: '100vh', background: 'gray' }}>
        <div className="d-flex align-items-center">
          <div className="selection-container d-flex align-items-center">
            <RangePicker variant='borderless' size="large" format={'DD-MM-YYYY'} onChange={(date, dateString) => {
              setBookingTime(dateString)
            }} />
            <IoPersonSharp className="ms-2" />
            <div className="ms-2 position-relative">
              <span style={{ cursor: 'pointer', userSelect: 'none' }} onClick={() => {
                setShowOption(prev => !prev)
              }}>{`${bookingData.adult} Adult | ${bookingData.children} Children | ${bookingData.room} Room`}
                <IoMdArrowDropdown /></span>
              {isShowOption && <div className="position-absolute dropdow-booking-data">
                <div className="d-flex justify-content-between">
                  <div>Adult</div>
                  <div>
                    <FiMinus onClick={() => { handleChangeNumber({ key: 'adult', value: -1 }) }} /> <input className="ms-3" type="number" min={1} max={20} step={1} value={bookingData.adult} /><GoPlus onClick={() => { handleChangeNumber({ key: 'adult', value: 1 }) }} />
                  </div>
                </div>
                <div className="d-flex justify-content-between">
                  <div>Children</div>
                  <div>
                    <FiMinus onClick={() => { handleChangeNumber({ key: 'child', value: -1 }) }} /> <input className="ms-3" type="number" min={1} max={20} step={1} value={bookingData.children} /><GoPlus onClick={() => { handleChangeNumber({ key: 'child', value: 1 }) }} />
                  </div>
                </div>
                <div className="d-flex justify-content-between">
                  <div>Room</div>
                  <div>
                    <FiMinus onClick={() => { handleChangeNumber({ key: 'room', value: -1 }) }} /> <input className="ms-3" type="number" min={1} max={99} step={1} value={bookingData.room} /><GoPlus onClick={() => { handleChangeNumber({ key: 'room', value: 1 }) }} />
                  </div>
                </div>
              </div>}
            </div>
          </div>
          <div onClick={handleBooking} className="btn-booking d-flex align-items-center">
            <span>
              Giữ chỗ ngay
              <FaArrowRightLong className="ms-1" />
            </span>
          </div>
        </div>
      </div >
    </>
  );
}
